sonar.projectKey=joaovfe_e2e-joaovfe
sonar.organization=joaovfe
sonar.projectName=Playwright E2E
sonar.projectVersion=1.0
sonar.sources=./src
sonar.exclusions=src/examples/**,src/utils/**
sonar.sourceEncoding=UTF-8